global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.Runtime.CompilerServices;
global using ClassFramework.Domain.Builders;
global using ClassFramework.Domain.Extensions;
global using CrossCutting.Common;
global using CrossCutting.Common.Extensions;
global using DatabaseFramework.Domain.Domains;
global using DataFramework.Domain.Extensions;
