namespace DataFramework.Pipelines.DatabaseEntityRetrieverSettingsProvider.Components.Abstractions;

public interface IDatabaseEntityRetrieverSettingsProviderComponentBuilder : IBuilder<IPipelineComponent<DatabaseEntityRetrieverSettingsProviderContext>>
{
}
