namespace DataFramework.ModelFramework.Tests;

public partial class IntegrationTests
{
    [Fact]
    public void Can_Generate_EntityBuilder_For_Poco()
    {
        // Arrange
        var settings = GeneratorSettings.Default;
        var dataObjectInfo = CreateDataObjectInfo(EntityClassType.Poco);
        var input = dataObjectInfo.ToEntityBuilderClass(settings);

        // Act
        var actual = GenerateCode(input, settings);

        // Assert
        actual.NormalizeLineEndings().Should().Be(@"// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace EntityBuilders
{
#nullable enable
    [System.CodeDom.Compiler.GeneratedCodeAttribute(@""DataFramework.ModelFramework.Generators.Entities.EntityBuilderGenerator"", @""1.0.0.0"")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
    public partial class TestEntityBuilder
    {
        [System.ComponentModel.DataAnnotations.Required]
        public int Id
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.Required]
        public string Name
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public string? Description
        {
            get;
            set;
        }

        [System.ComponentModel.ReadOnly(true)]
        public int? IdOriginal
        {
            get;
            set;
        }

        [System.ComponentModel.ReadOnly(true)]
        public string? NameOriginal
        {
            get;
            set;
        }

        [System.ComponentModel.ReadOnly(true)]
        public string? DescriptionOriginal
        {
            get;
            set;
        }

        public Entities.TestEntity Build()
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            #pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
            return new Entities.TestEntity { Id = Id, Name = Name, Description = Description, IdOriginal = IdOriginal, NameOriginal = NameOriginal, DescriptionOriginal = DescriptionOriginal };
            #pragma warning restore CS8600 // Converting null literal or possible null value to non-nullable type.
            #pragma warning restore CS8604 // Possible null reference argument.
        }

        public TestEntityBuilder WithId(int id)
        {
            Id = id;
            return this;
        }

        public TestEntityBuilder WithName(string name)
        {
            Name = name;
            return this;
        }

        public TestEntityBuilder WithDescription(string? description)
        {
            Description = description;
            return this;
        }

        public TestEntityBuilder WithIdOriginal(int? idOriginal)
        {
            IdOriginal = idOriginal;
            return this;
        }

        public TestEntityBuilder WithNameOriginal(string? nameOriginal)
        {
            NameOriginal = nameOriginal;
            return this;
        }

        public TestEntityBuilder WithDescriptionOriginal(string? descriptionOriginal)
        {
            DescriptionOriginal = descriptionOriginal;
            return this;
        }

        public TestEntityBuilder()
        {
            Id = default(System.Int32)!;
            Name = string.Empty;
        }

        public TestEntityBuilder(Entities.TestEntity source)
        {
            Id = source.Id;
            Name = source.Name;
            Description = source.Description;
            IdOriginal = source.IdOriginal;
            NameOriginal = source.NameOriginal;
            DescriptionOriginal = source.DescriptionOriginal;
        }
    }
#nullable restore
}
");
    }

    [Fact]
    public void Can_Generate_EntityBuilder_For_Record()
    {
        // Arrange
        var settings = GeneratorSettings.Default;
        var dataObjectInfo = CreateDataObjectInfo(EntityClassType.Record);
        var input = dataObjectInfo.ToEntityBuilderClass(settings);

        // Act
        var actual = GenerateCode(input, settings);

        // Assert
        actual.NormalizeLineEndings().Should().Be(@"// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace EntityBuilders
{
#nullable enable
    [System.CodeDom.Compiler.GeneratedCodeAttribute(@""DataFramework.ModelFramework.Generators.Entities.EntityBuilderGenerator"", @""1.0.0.0"")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
    public partial class TestEntityBuilder
    {
        [System.ComponentModel.DataAnnotations.Required]
        public int Id
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.Required]
        public string Name
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public string? Description
        {
            get;
            set;
        }

        public int? IdOriginal
        {
            get;
            set;
        }

        public string? NameOriginal
        {
            get;
            set;
        }

        public string? DescriptionOriginal
        {
            get;
            set;
        }

        public Entities.TestEntity Build()
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            #pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
            return new Entities.TestEntity(Id, Name, Description, IdOriginal, NameOriginal, DescriptionOriginal);
            #pragma warning restore CS8600 // Converting null literal or possible null value to non-nullable type.
            #pragma warning restore CS8604 // Possible null reference argument.
        }

        public TestEntityBuilder WithId(int id)
        {
            Id = id;
            return this;
        }

        public TestEntityBuilder WithName(string name)
        {
            Name = name;
            return this;
        }

        public TestEntityBuilder WithDescription(string? description)
        {
            Description = description;
            return this;
        }

        public TestEntityBuilder WithIdOriginal(int? idOriginal)
        {
            IdOriginal = idOriginal;
            return this;
        }

        public TestEntityBuilder WithNameOriginal(string? nameOriginal)
        {
            NameOriginal = nameOriginal;
            return this;
        }

        public TestEntityBuilder WithDescriptionOriginal(string? descriptionOriginal)
        {
            DescriptionOriginal = descriptionOriginal;
            return this;
        }

        public TestEntityBuilder()
        {
            Id = default(System.Int32)!;
            Name = string.Empty;
        }

        public TestEntityBuilder(Entities.TestEntity source)
        {
            Id = source.Id;
            Name = source.Name;
            Description = source.Description;
            IdOriginal = source.IdOriginal;
            NameOriginal = source.NameOriginal;
            DescriptionOriginal = source.DescriptionOriginal;
        }
    }
#nullable restore
}
");
    }

    [Fact]
    public void Can_Generate_EntityBuilder_For_ImmutableClass()
    {
        // Arrange
        var settings = GeneratorSettings.Default;
        var dataObjectInfo = CreateDataObjectInfo(EntityClassType.ImmutableClass);
        var input = dataObjectInfo.ToEntityBuilderClass(settings);

        // Act
        var actual = GenerateCode(input, settings);

        // Assert
        actual.NormalizeLineEndings().Should().Be(@"// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace EntityBuilders
{
#nullable enable
    [System.CodeDom.Compiler.GeneratedCodeAttribute(@""DataFramework.ModelFramework.Generators.Entities.EntityBuilderGenerator"", @""1.0.0.0"")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
    public partial class TestEntityBuilder
    {
        [System.ComponentModel.DataAnnotations.Required]
        public int Id
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.Required]
        public string Name
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public string? Description
        {
            get;
            set;
        }

        public int? IdOriginal
        {
            get;
            set;
        }

        public string? NameOriginal
        {
            get;
            set;
        }

        public string? DescriptionOriginal
        {
            get;
            set;
        }

        public Entities.TestEntity Build()
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            #pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
            return new Entities.TestEntity(Id, Name, Description, IdOriginal, NameOriginal, DescriptionOriginal);
            #pragma warning restore CS8600 // Converting null literal or possible null value to non-nullable type.
            #pragma warning restore CS8604 // Possible null reference argument.
        }

        public TestEntityBuilder WithId(int id)
        {
            Id = id;
            return this;
        }

        public TestEntityBuilder WithName(string name)
        {
            Name = name;
            return this;
        }

        public TestEntityBuilder WithDescription(string? description)
        {
            Description = description;
            return this;
        }

        public TestEntityBuilder WithIdOriginal(int? idOriginal)
        {
            IdOriginal = idOriginal;
            return this;
        }

        public TestEntityBuilder WithNameOriginal(string? nameOriginal)
        {
            NameOriginal = nameOriginal;
            return this;
        }

        public TestEntityBuilder WithDescriptionOriginal(string? descriptionOriginal)
        {
            DescriptionOriginal = descriptionOriginal;
            return this;
        }

        public TestEntityBuilder()
        {
            Id = default(System.Int32)!;
            Name = string.Empty;
        }

        public TestEntityBuilder(Entities.TestEntity source)
        {
            Id = source.Id;
            Name = source.Name;
            Description = source.Description;
            IdOriginal = source.IdOriginal;
            NameOriginal = source.NameOriginal;
            DescriptionOriginal = source.DescriptionOriginal;
        }
    }
#nullable restore
}
");
    }

    [Fact]
    public void Can_Generate_EntityBuilder_For_ObservablePoco()
    {
        // Arrange
        var settings = GeneratorSettings.Default;
        var dataObjectInfo = CreateDataObjectInfo(EntityClassType.ObservablePoco);
        var input = dataObjectInfo.ToEntityBuilderClass(settings);

        // Act
        var actual = GenerateCode(input, settings);

        // Assert
        actual.NormalizeLineEndings().Should().Be(@"// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace EntityBuilders
{
#nullable enable
    [System.CodeDom.Compiler.GeneratedCodeAttribute(@""DataFramework.ModelFramework.Generators.Entities.EntityBuilderGenerator"", @""1.0.0.0"")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
    public partial class TestEntityBuilder
    {
        [System.ComponentModel.DataAnnotations.Required]
        public int Id
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
                if (PropertyChanged != null) PropertyChanged(this, new PropertyChangedEventArgs(""Id""));
            }
        }

        [System.ComponentModel.DataAnnotations.Required]
        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
                if (PropertyChanged != null) PropertyChanged(this, new PropertyChangedEventArgs(""Name""));
            }
        }

        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public string? Description
        {
            get
            {
                return _description;
            }
            set
            {
                _description = value;
                if (PropertyChanged != null) PropertyChanged(this, new PropertyChangedEventArgs(""Description""));
            }
        }

        [System.ComponentModel.ReadOnly(true)]
        public int? IdOriginal
        {
            get
            {
                return _idOriginal;
            }
            set
            {
                _idOriginal = value;
                if (PropertyChanged != null) PropertyChanged(this, new PropertyChangedEventArgs(""Id""));
            }
        }

        [System.ComponentModel.ReadOnly(true)]
        public string? NameOriginal
        {
            get
            {
                return _nameOriginal;
            }
            set
            {
                _nameOriginal = value;
                if (PropertyChanged != null) PropertyChanged(this, new PropertyChangedEventArgs(""Name""));
            }
        }

        [System.ComponentModel.ReadOnly(true)]
        public string? DescriptionOriginal
        {
            get
            {
                return _descriptionOriginal;
            }
            set
            {
                _descriptionOriginal = value;
                if (PropertyChanged != null) PropertyChanged(this, new PropertyChangedEventArgs(""Description""));
            }
        }

        public Entities.TestEntity Build()
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            #pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
            return new Entities.TestEntity { Id = Id, Name = Name, Description = Description, IdOriginal = IdOriginal, NameOriginal = NameOriginal, DescriptionOriginal = DescriptionOriginal };
            #pragma warning restore CS8600 // Converting null literal or possible null value to non-nullable type.
            #pragma warning restore CS8604 // Possible null reference argument.
        }

        public TestEntityBuilder WithId(int id)
        {
            Id = id;
            return this;
        }

        public TestEntityBuilder WithName(string name)
        {
            Name = name;
            return this;
        }

        public TestEntityBuilder WithDescription(string? description)
        {
            Description = description;
            return this;
        }

        public TestEntityBuilder WithIdOriginal(int? idOriginal)
        {
            IdOriginal = idOriginal;
            return this;
        }

        public TestEntityBuilder WithNameOriginal(string? nameOriginal)
        {
            NameOriginal = nameOriginal;
            return this;
        }

        public TestEntityBuilder WithDescriptionOriginal(string? descriptionOriginal)
        {
            DescriptionOriginal = descriptionOriginal;
            return this;
        }

        public TestEntityBuilder()
        {
            Id = default(System.Int32)!;
            Name = string.Empty;
        }

        public TestEntityBuilder(Entities.TestEntity source)
        {
            Id = source.Id;
            Name = source.Name;
            Description = source.Description;
            IdOriginal = source.IdOriginal;
            NameOriginal = source.NameOriginal;
            DescriptionOriginal = source.DescriptionOriginal;
        }

        protected int _id;

        protected string _name;

        protected string? _description;

        protected bool _isExistingEntity;

        protected int? _idOriginal;

        protected string? _nameOriginal;

        protected string? _descriptionOriginal;

        protected bool? _isExistingEntityOriginal;

        protected event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    }
#nullable restore
}
");
    }

    [Fact]
    public void Can_Generate_EntityBuilder_For_Entity_With_Collection()
    {
        // Arrange
        var settings = GeneratorSettings.Default;
        var dataObjectInfo = CreateDataObjectInfoWithCollectionField();
        var input = dataObjectInfo.ToEntityBuilderClass(settings);

        // Act
        var actual = GenerateCode(input, settings);

        // Assert
        actual.NormalizeLineEndings().Should().Be(@"// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace GeneratedNamespace
{
#nullable enable
    [System.CodeDom.Compiler.GeneratedCodeAttribute(@""DataFramework.ModelFramework.Generators.Entities.EntityBuilderGenerator"", @""1.0.0.0"")]
    public partial class TestEntityBuilder
    {
        [System.ComponentModel.DataAnnotations.Required]
        public long Id
        {
            get;
            set;
        }

        public System.Collections.Generic.List<string> Tags
        {
            get;
            set;
        }

        public TestEntity Build()
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            #pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
            return new TestEntity { Id = Id, Tags = Tags };
            #pragma warning restore CS8600 // Converting null literal or possible null value to non-nullable type.
            #pragma warning restore CS8604 // Possible null reference argument.
        }

        public TestEntityBuilder WithId(long id)
        {
            Id = id;
            return this;
        }

        public TestEntityBuilder AddTags(System.Collections.Generic.IEnumerable<string> tags)
        {
            return AddTags(tags.ToArray());
        }

        public TestEntityBuilder AddTags(params string[] tags)
        {
            Tags.AddRange(tags);
            return this;
        }

        public TestEntityBuilder()
        {
            Tags = new System.Collections.Generic.List<string>();
            Id = default(System.Int64)!;
        }

        public TestEntityBuilder(TestEntity source)
        {
            Tags = new System.Collections.Generic.List<string>();
            Id = source.Id;
            Tags.AddRange(source.Tags);
        }
    }
#nullable restore
}
");
    }
}
