using CrossCutting.Common.Extensions;
using DataFramework.ModelFramework.Extensions;
using FluentAssertions;
using Xunit;

namespace DataFramework.ModelFramework.Tests
{
    public partial class IntegrationTests
    {
        [Fact]
        public void Can_Generate_EntityRetrieverSettings()
        {
            // Arrange
            var settings = GeneratorSettings.Default;
            var input = CreateDataObjectInfo(default(EntityClassType)).ToEntityRetrieverSettingsClass(settings);

            // Act
            var actual = GenerateCode(input, settings);

            // Assert
            actual.NormalizeLineEndings().Should().Be(@"// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace EntityRetrieverSettings
{
#nullable enable
    [System.CodeDom.Compiler.GeneratedCode(@""DataFramework.ModelFramework.Generators.EntityRetrieverSettingsGenerator"", @""1.0.0.0"")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
    internal partial class TestEntityPagedEntityRetrieverSettings : CrossCutting.Data.Abstractions.IPagedDatabaseEntityRetrieverSettings
    {
        public string TableName
        {
            get
            {
                return @""TestEntity"";
            }
        }

        public string Fields
        {
            get
            {
                return @""Id, Name, Description"";
            }
        }

        public string DefaultOrderBy
        {
            get
            {
                return @"""";
            }
        }

        public string DefaultWhere
        {
            get
            {
                return @"""";
            }
        }

        public System.Nullable<int> OverridePageSize
        {
            get
            {
                return -1;
            }
        }
    }
#nullable restore
}
");
        }
    }
}
