// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.2
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DataFramework.Core.Builders
{
#nullable enable
    public partial class DataObjectInfoBuilder
    {
        public System.Collections.Generic.List<DataFramework.Core.Builders.FieldInfoBuilder> Fields
        {
            get;
            set;
        }

        public string? AssemblyName
        {
            get;
            set;
        }

        public string? TypeName
        {
            get;
            set;
        }

        public string Name
        {
            get;
            set;
        }

        public string? Description
        {
            get;
            set;
        }

        public string? DisplayName
        {
            get;
            set;
        }

        public bool IsVisible
        {
            get;
            set;
        }

        public bool IsReadOnly
        {
            get;
            set;
        }

        public bool IsQueryable
        {
            get;
            set;
        }

        public System.Collections.Generic.List<DataFramework.Core.Builders.MetadataBuilder> Metadata
        {
            get;
            set;
        }

        public DataFramework.Abstractions.IDataObjectInfo Build()
        {
            return new DataFramework.Core.DataObjectInfo(Fields.Select(x => x.Build()), AssemblyName, TypeName, Name, Description, DisplayName, IsVisible, IsReadOnly, IsQueryable, Metadata.Select(x => x.Build()));
        }

        public DataObjectInfoBuilder AddFields(System.Collections.Generic.IEnumerable<DataFramework.Core.Builders.FieldInfoBuilder> fields)
        {
            return AddFields(fields.ToArray());
        }

        public DataObjectInfoBuilder AddFields(params DataFramework.Core.Builders.FieldInfoBuilder[] fields)
        {
            Fields.AddRange(fields);
            return this;
        }

        public DataObjectInfoBuilder WithAssemblyName(string? assemblyName)
        {
            AssemblyName = assemblyName;
            return this;
        }

        public DataObjectInfoBuilder WithTypeName(string? typeName)
        {
            TypeName = typeName;
            return this;
        }

        public DataObjectInfoBuilder WithType(System.Type? type)
        {
            TypeName = type?.AssemblyQualifiedName;
            return this;
        }

        public DataObjectInfoBuilder WithName(string name)
        {
            Name = name;
            return this;
        }

        public DataObjectInfoBuilder WithDescription(string? description)
        {
            Description = description;
            return this;
        }

        public DataObjectInfoBuilder WithDisplayName(string? displayName)
        {
            DisplayName = displayName;
            return this;
        }

        public DataObjectInfoBuilder WithIsVisible(bool isVisible = true)
        {
            IsVisible = isVisible;
            return this;
        }

        public DataObjectInfoBuilder WithIsReadOnly(bool isReadOnly = true)
        {
            IsReadOnly = isReadOnly;
            return this;
        }

        public DataObjectInfoBuilder WithIsQueryable(bool isQueryable = true)
        {
            IsQueryable = isQueryable;
            return this;
        }

        public DataObjectInfoBuilder AddMetadata(System.Collections.Generic.IEnumerable<DataFramework.Core.Builders.MetadataBuilder> metadata)
        {
            return AddMetadata(metadata.ToArray());
        }

        public DataObjectInfoBuilder AddMetadata(params DataFramework.Core.Builders.MetadataBuilder[] metadata)
        {
            Metadata.AddRange(metadata);
            return this;
        }

        public DataObjectInfoBuilder AddMetadata(string name, object? value)
        {
            AddMetadata(new DataFramework.Core.Builders.MetadataBuilder().WithName(name).WithValue(value));
            return this;
        }

        public DataObjectInfoBuilder()
        {
            Fields = new System.Collections.Generic.List<DataFramework.Core.Builders.FieldInfoBuilder>();
            Metadata = new System.Collections.Generic.List<DataFramework.Core.Builders.MetadataBuilder>();
            Name = string.Empty;
            IsVisible = true;
            IsReadOnly = default;
            IsQueryable = true;
        }

        public DataObjectInfoBuilder(DataFramework.Abstractions.IDataObjectInfo source)
        {
            Fields = new System.Collections.Generic.List<DataFramework.Core.Builders.FieldInfoBuilder>();
            Metadata = new System.Collections.Generic.List<DataFramework.Core.Builders.MetadataBuilder>();
            Fields.AddRange(source.Fields.Select(x => new DataFramework.Core.Builders.FieldInfoBuilder(x)));
            AssemblyName = source.AssemblyName;
            TypeName = source.TypeName;
            Name = source.Name;
            Description = source.Description;
            DisplayName = source.DisplayName;
            IsVisible = source.IsVisible;
            IsReadOnly = source.IsReadOnly;
            IsQueryable = source.IsQueryable;
            Metadata.AddRange(source.Metadata.Select(x => new DataFramework.Core.Builders.MetadataBuilder(x)));
        }
    }
#nullable restore
}

