// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 7.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DataFramework.Core.Builders
{
#nullable enable
    public partial class DataObjectInfoBuilder : System.ComponentModel.DataAnnotations.IValidatableObject
    {
        public System.Collections.Generic.List<DataFramework.Core.Builders.FieldInfoBuilder> Fields
        {
            get;
            set;
        }

        public System.Text.StringBuilder? AssemblyName
        {
            get
            {
                return _assemblyNameDelegate.Value;
            }
            set
            {
                _assemblyNameDelegate = new (() => value);
            }
        }

        public System.Text.StringBuilder? TypeName
        {
            get
            {
                return _typeNameDelegate.Value;
            }
            set
            {
                _typeNameDelegate = new (() => value);
            }
        }

        public System.Text.StringBuilder Name
        {
            get
            {
                return _nameDelegate.Value;
            }
            set
            {
                _nameDelegate = new (() => value);
            }
        }

        public System.Text.StringBuilder? Description
        {
            get
            {
                return _descriptionDelegate.Value;
            }
            set
            {
                _descriptionDelegate = new (() => value);
            }
        }

        public System.Text.StringBuilder? DisplayName
        {
            get
            {
                return _displayNameDelegate.Value;
            }
            set
            {
                _displayNameDelegate = new (() => value);
            }
        }

        public bool IsVisible
        {
            get
            {
                return _isVisibleDelegate.Value;
            }
            set
            {
                _isVisibleDelegate = new (() => value);
            }
        }

        public bool IsReadOnly
        {
            get
            {
                return _isReadOnlyDelegate.Value;
            }
            set
            {
                _isReadOnlyDelegate = new (() => value);
            }
        }

        public bool IsQueryable
        {
            get
            {
                return _isQueryableDelegate.Value;
            }
            set
            {
                _isQueryableDelegate = new (() => value);
            }
        }

        public System.Collections.Generic.List<DataFramework.Core.Builders.MetadataBuilder> Metadata
        {
            get;
            set;
        }

        public DataFramework.Abstractions.IDataObjectInfo Build()
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            #pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
            return new DataFramework.Core.DataObjectInfo(Fields.Select(x => x.Build()), AssemblyName?.ToString(), TypeName?.ToString(), Name?.ToString(), Description?.ToString(), DisplayName?.ToString(), IsVisible, IsReadOnly, IsQueryable, Metadata.Select(x => x.Build()));
            #pragma warning restore CS8600 // Converting null literal or possible null value to non-nullable type.
            #pragma warning restore CS8604 // Possible null reference argument.
        }

        public System.Collections.Generic.IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(System.ComponentModel.DataAnnotations.ValidationContext validationContext)
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            #pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
            var instance = new DataFramework.Core.DataObjectInfoBase(Fields.Select(x => x.Build()), AssemblyName?.ToString(), TypeName?.ToString(), Name?.ToString(), Description?.ToString(), DisplayName?.ToString(), IsVisible, IsReadOnly, IsQueryable, Metadata.Select(x => x.Build()));
            #pragma warning restore CS8600 // Converting null literal or possible null value to non-nullable type.
            #pragma warning restore CS8604 // Possible null reference argument.
            var results = new System.Collections.Generic.List<System.ComponentModel.DataAnnotations.ValidationResult>();
            System.ComponentModel.DataAnnotations.Validator.TryValidateObject(instance, new System.ComponentModel.DataAnnotations.ValidationContext(instance, null, null), results, true);
            return results;
        }

        public DataObjectInfoBuilder AddFields(System.Collections.Generic.IEnumerable<DataFramework.Core.Builders.FieldInfoBuilder> fields)
        {
            return AddFields(fields.ToArray());
        }

        public DataObjectInfoBuilder AddFields(params DataFramework.Core.Builders.FieldInfoBuilder[] fields)
        {
            Fields.AddRange(fields);
            return this;
        }

        public DataObjectInfoBuilder WithAssemblyName(System.Text.StringBuilder? assemblyName)
        {
            AssemblyName = assemblyName;
            return this;
        }

        public DataObjectInfoBuilder WithAssemblyName(System.Func<System.Text.StringBuilder?> assemblyNameDelegate)
        {
            _assemblyNameDelegate = new (assemblyNameDelegate);
            return this;
        }

        public DataObjectInfoBuilder WithAssemblyName(string value)
        {
            if (AssemblyName == null)
                AssemblyName = new System.Text.StringBuilder();
            AssemblyName.Clear().Append(value);
            return this;
        }

        public DataObjectInfoBuilder AppendToAssemblyName(string value)
        {
            if (AssemblyName == null)
                AssemblyName = new System.Text.StringBuilder();
            AssemblyName.Append(value);
            return this;
        }

        public DataObjectInfoBuilder AppendLineToAssemblyName(string value)
        {
            if (AssemblyName == null)
                AssemblyName = new System.Text.StringBuilder();
            AssemblyName.AppendLine(value);
            return this;
        }

        public DataObjectInfoBuilder WithTypeName(System.Text.StringBuilder? typeName)
        {
            TypeName = typeName;
            return this;
        }

        public DataObjectInfoBuilder WithTypeName(System.Func<System.Text.StringBuilder?> typeNameDelegate)
        {
            _typeNameDelegate = new (typeNameDelegate);
            return this;
        }

        public DataObjectInfoBuilder WithTypeName(string value)
        {
            if (TypeName == null)
                TypeName = new System.Text.StringBuilder();
            TypeName.Clear().Append(value);
            return this;
        }

        public DataObjectInfoBuilder AppendToTypeName(string value)
        {
            if (TypeName == null)
                TypeName = new System.Text.StringBuilder();
            TypeName.Append(value);
            return this;
        }

        public DataObjectInfoBuilder AppendLineToTypeName(string value)
        {
            if (TypeName == null)
                TypeName = new System.Text.StringBuilder();
            TypeName.AppendLine(value);
            return this;
        }

        public DataObjectInfoBuilder WithType(System.Type type)
        {
            WithTypeName(type?.AssemblyQualifiedName!);
            return this;
        }

        public DataObjectInfoBuilder WithName(System.Text.StringBuilder name)
        {
            Name = name;
            return this;
        }

        public DataObjectInfoBuilder WithName(System.Func<System.Text.StringBuilder> nameDelegate)
        {
            _nameDelegate = new (nameDelegate);
            return this;
        }

        public DataObjectInfoBuilder WithName(string value)
        {
            if (Name == null)
                Name = new System.Text.StringBuilder();
            Name.Clear().Append(value);
            return this;
        }

        public DataObjectInfoBuilder AppendToName(string value)
        {
            if (Name == null)
                Name = new System.Text.StringBuilder();
            Name.Append(value);
            return this;
        }

        public DataObjectInfoBuilder AppendLineToName(string value)
        {
            if (Name == null)
                Name = new System.Text.StringBuilder();
            Name.AppendLine(value);
            return this;
        }

        public DataObjectInfoBuilder WithDescription(System.Text.StringBuilder? description)
        {
            Description = description;
            return this;
        }

        public DataObjectInfoBuilder WithDescription(System.Func<System.Text.StringBuilder?> descriptionDelegate)
        {
            _descriptionDelegate = new (descriptionDelegate);
            return this;
        }

        public DataObjectInfoBuilder WithDescription(string value)
        {
            if (Description == null)
                Description = new System.Text.StringBuilder();
            Description.Clear().Append(value);
            return this;
        }

        public DataObjectInfoBuilder AppendToDescription(string value)
        {
            if (Description == null)
                Description = new System.Text.StringBuilder();
            Description.Append(value);
            return this;
        }

        public DataObjectInfoBuilder AppendLineToDescription(string value)
        {
            if (Description == null)
                Description = new System.Text.StringBuilder();
            Description.AppendLine(value);
            return this;
        }

        public DataObjectInfoBuilder WithDisplayName(System.Text.StringBuilder? displayName)
        {
            DisplayName = displayName;
            return this;
        }

        public DataObjectInfoBuilder WithDisplayName(System.Func<System.Text.StringBuilder?> displayNameDelegate)
        {
            _displayNameDelegate = new (displayNameDelegate);
            return this;
        }

        public DataObjectInfoBuilder WithDisplayName(string value)
        {
            if (DisplayName == null)
                DisplayName = new System.Text.StringBuilder();
            DisplayName.Clear().Append(value);
            return this;
        }

        public DataObjectInfoBuilder AppendToDisplayName(string value)
        {
            if (DisplayName == null)
                DisplayName = new System.Text.StringBuilder();
            DisplayName.Append(value);
            return this;
        }

        public DataObjectInfoBuilder AppendLineToDisplayName(string value)
        {
            if (DisplayName == null)
                DisplayName = new System.Text.StringBuilder();
            DisplayName.AppendLine(value);
            return this;
        }

        public DataObjectInfoBuilder WithIsVisible(bool isVisible = true)
        {
            IsVisible = isVisible;
            return this;
        }

        public DataObjectInfoBuilder WithIsVisible(System.Func<bool> isVisibleDelegate)
        {
            _isVisibleDelegate = new (isVisibleDelegate);
            return this;
        }

        public DataObjectInfoBuilder WithIsReadOnly(bool isReadOnly = true)
        {
            IsReadOnly = isReadOnly;
            return this;
        }

        public DataObjectInfoBuilder WithIsReadOnly(System.Func<bool> isReadOnlyDelegate)
        {
            _isReadOnlyDelegate = new (isReadOnlyDelegate);
            return this;
        }

        public DataObjectInfoBuilder WithIsQueryable(bool isQueryable = true)
        {
            IsQueryable = isQueryable;
            return this;
        }

        public DataObjectInfoBuilder WithIsQueryable(System.Func<bool> isQueryableDelegate)
        {
            _isQueryableDelegate = new (isQueryableDelegate);
            return this;
        }

        public DataObjectInfoBuilder AddMetadata(System.Collections.Generic.IEnumerable<DataFramework.Core.Builders.MetadataBuilder> metadata)
        {
            return AddMetadata(metadata.ToArray());
        }

        public DataObjectInfoBuilder AddMetadata(params DataFramework.Core.Builders.MetadataBuilder[] metadata)
        {
            Metadata.AddRange(metadata);
            return this;
        }

        public DataObjectInfoBuilder AddMetadata(string name, object? value)
        {
            AddMetadata(new MetadataBuilder().WithName(name).WithValue(value));
            return this;
        }

        public DataObjectInfoBuilder()
        {
            Fields = new System.Collections.Generic.List<DataFramework.Core.Builders.FieldInfoBuilder>();
            Metadata = new System.Collections.Generic.List<DataFramework.Core.Builders.MetadataBuilder>();
            #pragma warning disable CS8603 // Possible null reference return.
            _assemblyNameDelegate = new (() => default);
            _typeNameDelegate = new (() => default);
            _nameDelegate = new (() => new System.Text.StringBuilder());
            _descriptionDelegate = new (() => default);
            _displayNameDelegate = new (() => default);
            _isVisibleDelegate = new (() => true);
            _isReadOnlyDelegate = new (() => default(bool));
            _isQueryableDelegate = new (() => true);
            #pragma warning restore CS8603 // Possible null reference return.
        }

        public DataObjectInfoBuilder(DataFramework.Abstractions.IDataObjectInfo source)
        {
            Fields = new System.Collections.Generic.List<DataFramework.Core.Builders.FieldInfoBuilder>();
            Metadata = new System.Collections.Generic.List<DataFramework.Core.Builders.MetadataBuilder>();
            Fields.AddRange(source.Fields.Select(x => new DataFramework.Core.Builders.FieldInfoBuilder(x)));
            _assemblyNameDelegate = new (() => new System.Text.StringBuilder(source.AssemblyName));
            _typeNameDelegate = new (() => new System.Text.StringBuilder(source.TypeName));
            _nameDelegate = new (() => new System.Text.StringBuilder(source.Name));
            _descriptionDelegate = new (() => new System.Text.StringBuilder(source.Description));
            _displayNameDelegate = new (() => new System.Text.StringBuilder(source.DisplayName));
            _isVisibleDelegate = new (() => source.IsVisible);
            _isReadOnlyDelegate = new (() => source.IsReadOnly);
            _isQueryableDelegate = new (() => source.IsQueryable);
            Metadata.AddRange(source.Metadata.Select(x => new DataFramework.Core.Builders.MetadataBuilder(x)));
        }

        protected System.Lazy<System.Text.StringBuilder?> _assemblyNameDelegate;

        protected System.Lazy<System.Text.StringBuilder?> _typeNameDelegate;

        protected System.Lazy<System.Text.StringBuilder> _nameDelegate;

        protected System.Lazy<System.Text.StringBuilder?> _descriptionDelegate;

        protected System.Lazy<System.Text.StringBuilder?> _displayNameDelegate;

        protected System.Lazy<bool> _isVisibleDelegate;

        protected System.Lazy<bool> _isReadOnlyDelegate;

        protected System.Lazy<bool> _isQueryableDelegate;
    }
#nullable restore
}

