// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.2
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DataFramework.Core.Builders
{
#nullable enable
    public partial class MetadataBuilder
    {
        public string Name
        {
            get;
            set;
        }

        public object? Value
        {
            get;
            set;
        }

        public DataFramework.Abstractions.IMetadata Build()
        {
            return new DataFramework.Core.Metadata(Name, Value);
        }

        public MetadataBuilder WithName(string name)
        {
            Name = name;
            return this;
        }

        public MetadataBuilder WithValue(object? value)
        {
            Value = value;
            return this;
        }

        public MetadataBuilder()
        {
            Name = string.Empty;
        }

        public MetadataBuilder(DataFramework.Abstractions.IMetadata source)
        {
            Name = source.Name;
            Value = source.Value;
        }
    }
#nullable restore
}

