namespace DataFramework.Pipelines.PagedEntityRetrieverSettingss.Components.Abstractions;

public interface IPagedEntityRetrieverSettingsComponentBuilder : IBuilder<IPipelineComponent<PagedEntityRetrieverSettingsContext>>
{
}
