namespace DataFramework.Pipelines.PagedEntityRetrieverSettings.Components.Abstractions;

public interface IPagedEntityRetrieverSettingsComponentBuilder : IBuilder<IPipelineComponent<PagedEntityRetrieverSettingsContext>>
{
}
