// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 7.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DataFramework.Core
{
#nullable enable
    public partial record DataObjectInfoBase : DataFramework.Abstractions.IDataObjectInfo
    {
        public System.Collections.Generic.IReadOnlyCollection<DataFramework.Abstractions.IFieldInfo> Fields
        {
            get;
            private set;
        }

        public string? AssemblyName
        {
            get;
            private set;
        }

        public string? TypeName
        {
            get;
            private set;
        }

        public string Name
        {
            get;
            private set;
        }

        public string? Description
        {
            get;
            private set;
        }

        public string? DisplayName
        {
            get;
            private set;
        }

        public bool IsVisible
        {
            get;
            private set;
        }

        public bool IsReadOnly
        {
            get;
            private set;
        }

        public bool IsQueryable
        {
            get;
            private set;
        }

        public System.Collections.Generic.IReadOnlyCollection<DataFramework.Abstractions.IMetadata> Metadata
        {
            get;
            private set;
        }

        public DataObjectInfoBase(System.Collections.Generic.IEnumerable<DataFramework.Abstractions.IFieldInfo> fields, string? assemblyName, string? typeName, string name, string? description, string? displayName, bool isVisible, bool isReadOnly, bool isQueryable, System.Collections.Generic.IEnumerable<DataFramework.Abstractions.IMetadata> metadata)
        {
            this.Fields = new CrossCutting.Common.ValueCollection<DataFramework.Abstractions.IFieldInfo>(fields);
            this.AssemblyName = assemblyName;
            this.TypeName = typeName;
            this.Name = name;
            this.Description = description;
            this.DisplayName = displayName;
            this.IsVisible = isVisible;
            this.IsReadOnly = isReadOnly;
            this.IsQueryable = isQueryable;
            this.Metadata = new CrossCutting.Common.ValueCollection<DataFramework.Abstractions.IMetadata>(metadata);
        }
    }
#nullable restore
}

