namespace DataFramework.Pipelines.DatabaseEntityRetrieverProvider.Components.Abstractions;

public interface IDatabaseEntityRetrieverProviderComponentBuilder : IBuilder<IPipelineComponent<DatabaseEntityRetrieverProviderContext>>
{
}
